server:
  port: 8083

spring:
  docker:
    compose:
      enabled: false
  grpc:
    server:
      port: 9093

ollama:
  url: ${OLLAMA_URL:http://localhost:11434}

llm:
  provider: groq
  preprocessprovider: groq

gemini:
  api-key: ${GEMINI_API_KEY:AIzaSyCcDZJ1Uh5MCKDPLUnrPQYK5QJXNQ_SvpA}
  url: https://generativelanguage.googleapis.com
  model: gemini-2.0-flash

groq:
  api-key: ${GROQ_API_KEY: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}
  url: https://api.groq.com
  model: llama-3.1-8b-instant