spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  grpc:
    client:
      channels:
        rag-service:
          address: static://localhost:9092
          negotiation-type: plaintext
        llm-service: # ← новый канал
          address: static://localhost:9093
          negotiation-type: plaintext
logging:
  level:
    org.apache.fontbox: ERROR
    org.apache.pdfbox: ERROR
llm:
  stream:
    protocol: ${LLM_STREAM_PROTOCOL:rest} # rest или grpc