spring.application.name=LlmChatRag
server.port=8080
qdrant.service.url=http://localhost:8085
llm.service.url=http://localhost:8083
spring.grpc.client.channels.rag-service.address=static://localhost:9090
spring.grpc.client.channels.rag-service.negotiation-type=plaintext
# ???????? ???????? ??????????: rest ??? grpc
document.upload.protocol=rest
search.protocol=rest