spring.application.name=QdrantService
server.port=8085
spring.grpc.server.port=9090
# vector, keyword, hybrid
qdrant.search-type=vector
#single or  batch
chunker.embedding.mode=batch

# Strategy chunks(semantic, fixed, recursive)
chunking.strategy = fixed

# Nastroiki Fixed-size
chunking.fixed.size=900
chunking.fixed.overlap=250

# Nastoriki Recursive
chunking.recursive.max-size=900
chunking.recursive.overlap=250